<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Análise de Dados: Fundamentos de Aprendizado de Máquina
Caderno de **Exercícios**<br> 
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Teoria;</li>
  <li>Atributos categóricos;</li>
  <li>Atributos numéricos;</li>
  <li>Dados faltantes.</li>
</ol>

---

# **Exercícios**

## 1\. Pinguins

Neste exercício, vamos utilizar uma base de dados com informações sobre penguins. A idéia é preparar a base de dados para prever a espécie do penguin (variável resposta) baseado em suas características físicas e geográficas (variáveis preditivas).

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [35]:
data = sns.load_dataset('penguins')

In [36]:
# ha muitos dados faltantes 
data.head(n=10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,Female
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN

In [ ]:
data.info

### **1.1. Valores nulos**

In [37]:
# analise exploratoria 

dados_faltantes_total = data.isnull().any().any()
print( dados_faltantes_total)

#data.describe()
#data = data.dropna()

True

In [ ]:
data.head(n=24)

A base de dados possui valores faltantes, utilize os conceitos da aula para trata-los.

In [38]:
# resposta da questão 1.1

# Nos valores numericos substitui os dados faltantes pela media.
# mesmo assim há varias linha com  dados faltantes pricpalmente na coluna 
# na coluna  sex.

df = pd.DataFrame(data)

# Substituir os valores faltantes pela média em cada coluna
for coluna in df.columns:
    if df[coluna].dtype == 'float64':  # Verifica se a coluna contém números de ponto flutuante
        media_coluna = df[coluna].mean()
        df[coluna].fillna(media_coluna, inplace=True)

In [ ]:
data.info
#data.head(n=10)
# 344 rows x 7 columns

In [ ]:
# descartando as linhas com dados faltantes 
data.dropna()

# depois de descarta as linha, 
#sobram 333 linhas 10 a menos 
data.info

### **1.2. Variáveis numéricas**

Identifique as variáveis numéricas e crie uma nova coluna **padronizando** seus valores. A nova coluna deve ter o mesmo nome da coluna original acrescidade de "*_std*".

> **Nota**: Você não deve tratar a variável resposta.

In [41]:
# resposta da questão 1.2

# coletando o desvio padrão das variaveis numericas 
data.head(n=1)

md_length = data['bill_length_mm'].mean()


dp_length = data['bill_length_mm'].std()
dp_depth = data['bill_depth_mm'].std()
dp_flipper = data['flipper_length_mm'].std()
dp_body = data['body_mass_g'].std()

In [42]:
#retornando as novas colunas padronizadas

data['bill_length_mm_std'] = data['bill_length_mm'].apply(lambda mm : (mm - md_length) / dp_length)

In [43]:
data.head(n=1)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_length_mm_std
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,-0.885791

### **1.3. Variáveis categóricas**

Identifique as variáveis categóricas nominais e ordinais, crie uma nova coluna aplicando a técnica correta de conversão a seus valores. A nova coluna deve ter o mesmo nome da coluna original acrescidade de "*_nom*" ou "*_ord*".

> **Nota**: Você não deve tratar a variável resposta.

In [ ]:
# resposta da questão 1.3

### **1.4. Limpeza**

Descarte as colunas originais e mantenha apenas a variável resposta e as variáveis preditivas com o sufixo *_std*", *_nom*" e "*_ord*".

In [ ]:
# resposta da questão 1.4

---