<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Análise de Dados: Fundamentos de Aprendizado de Máquina
Caderno de **Exercícios**<br> 
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Teoria;</li>
  <li>Atributos categóricos;</li>
  <li>Atributos numéricos;</li>
  <li>Dados faltantes.</li>
</ol>

---

# **Exercícios**

## 1\. Pinguins

Neste exercício, vamos utilizar uma base de dados com informações sobre penguins. A idéia é preparar a base de dados para prever a espécie do penguin (variável resposta) baseado em suas características físicas e geográficas (variáveis preditivas).

In [36]:
import numpy as np
import pandas as pd
import seaborn as sns

In [57]:
data = sns.load_dataset('penguins')

In [58]:
# ha muitos dados faltantes 
data.head(n=10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,Female
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN

In [ ]:
data.info

### **1.1. Valores nulos**

In [59]:
# analise exploratoria 

dados_faltantes_total = data.isnull().any().any()
print( dados_faltantes_total)

#data.describe()
#data = data.dropna()

True

In [ ]:
data.head(n=24)

A base de dados possui valores faltantes, utilize os conceitos da aula para trata-los.

In [60]:
# resposta da questão 1.1

# Nos valores numericos substitui os dados faltantes pela media.
# mesmo assim há varias linha com  dados faltantes pricpalmente na coluna 
# na coluna  sex.

df = pd.DataFrame(data)

# Substituir os valores faltantes pela média em cada coluna
for coluna in df.columns:
    if df[coluna].dtype == 'float64':  # Verifica se a coluna contém números de ponto flutuante
        media_coluna = df[coluna].mean()
        df[coluna].fillna(media_coluna, inplace=True)

In [ ]:
# na etapa anterior foram incluidas as medias na colunas 
# numericas onde havia dados faltantes.
# o dataframe mudou de nome de data para df.

df.info
#data.head(n=10)
# 344 rows x 7 columns

In [62]:


# depois de descarta as linha, 
#sobram 333 linhas 10 a menos 
df_limp = df.dropna()

In [63]:
# descartando as linhas com dados faltantes 
#sobram 333 linhas 10 a menos 
df_limp.tail(n=5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [64]:
dados_faltantes_total = df_limp.isnull().any().any()
print( dados_faltantes_total)

False

### **1.2. Variáveis numéricas**

Identifique as variáveis numéricas e crie uma nova coluna **padronizando** seus valores. A nova coluna deve ter o mesmo nome da coluna original acrescidade de "*_std*".

> **Nota**: Você não deve tratar a variável resposta.

In [53]:
# resposta da questão 1.2

# Variavel resposta sera "species" - A especie do pinguin !

# colunas normalizada Dp nessa etapa 
# bill_length_mm , bill_depth_mm , flipper_length_mm , body_mass_g !.

# coletando o desvio padrão das variaveis numericas 
df_limp.head(n=1)

md_length = df_limp['bill_length_mm'].mean()
md_depth = df_limp['bill_depth_mm'].mean()
md_flipper = df_limp['flipper_length_mm'].mean()
md_body = df_limp['body_mass_g'].mean()

dp_length = df_limp['bill_length_mm'].std()
dp_depth = df_limp['bill_depth_mm'].std()
dp_flipper = df_limp['flipper_length_mm'].std()
dp_body = df_limp['body_mass_g'].std()

In [ ]:
# Retornando as novas colunas padronizadas
# aplicando a  media e desvio padrõa 
df_limp['bill_length_mm_std'] = df_limp['bill_length_mm'].apply(lambda mm : (mm - md_length) / dp_length)
df_limp['bill_depth_mm_std'] = df_limp['bill_depth_mm'].apply(lambda mm : (mm - md_depth) / dp_depth)
df_limp['flipper_length_mm_std'] = df_limp['flipper_length_mm'].apply(lambda mm : (mm - md_flipper) / dp_flipper)
df_limp['body_mass_g_std'] = df_limp['body_mass_g'].apply(lambda mm : (mm - md_body) / dp_body)

In [72]:
#df_limp.head(n=10)

teste = df_limp[['flipper_length_mm_std']].max()
print(teste)

flipper_length_mm_std    2.142804
dtype: float64

### **1.3. Variáveis categóricas**

Identifique as variáveis categóricas nominais e ordinais, crie uma nova coluna aplicando a técnica correta de conversão a seus valores. A nova coluna deve ter o mesmo nome da coluna original acrescidade de "*_nom*" ou "*_ord*".

> **Nota**: Você não deve tratar a variável resposta.

Variável respota "species"

In [ ]:
# resposta da questão 1.3

# Variaveis Categoricas norminais e ordnais 
# São as de tipo string 


# Atributos categóricos ordinais são aqueles em que os valores apresentem relação de ordem.
# Visto que as variavel island não apresenta ordem o codigo a baixo seria mesmo o ideal ?
# visto que uma ilha não e maior ou melhor que a outra 

#df_limp['island'].drop_duplicates()

island_mapper = {
    "Torgersen": 0,
    "Biscoe": 1,
    "Dream" : 2
}


df_limp['island_ord'] = df_limp['island'].apply(lambda level : island_mapper[level])

In [ ]:
# respota mais aceitavel para a coluna "island"
# nesse atividade não apresenta categoria ordinal

islanda_teste = pd.get_dummies(df_limp['island'])
islanda_teste.columns = [ str(col) + '_nrm'  for col in islanda_teste.columns]
print(islanda_teste)



df_limp = pd.concat([df_limp,islanda_teste], axis=1)

# Quase esqueci da coluna "sex"

sex_m = pd.get_dummies(df_limp['sex'])
sex_m.columns = [ str(col) + '_nrm'  for col in sex_m.columns]
print(sex_m)



df_limp = pd.concat([df_limp,sex_m], axis=1)

### **1.4. Limpeza**

Descarte as colunas originais e mantenha apenas a variável resposta e as variáveis preditivas com o sufixo *_std*", *_nom*" e "*_ord*".

In [ ]:
# resposta da questão 1.4


#df_limp.head(n=1)

#df_limp['sex'].describe()



df_limp  = df_limp.drop(columns=['island','body_mass_g','bill_length_mm','bill_depth_mm','flipper_length_mm','sex'],axis=1)

In [ ]:
df_limp.info

In [114]:
df_limp.to_csv('pinguin_pre_parado.csv')

---